sudo: required

services:
    - docker

script:
    - mkdir _site
    - docker-compose run build jekyll build

deploy:
  provider: s3
  access_key_id: "$ACCESS_KEY"
  secret_access_key: "$SECRET_KEY"
  bucket: "pwd-training-site"
  acl: public_read
  local_dir: _site
  on:
      branch: master
